#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Retakeem.Resource", IsApplication=true)]

namespace Retakeem
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int theme_devicedefault_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int clap_board = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070008
			public const int MyButton = 2131165192;
			
			// aapt resource value: 0x7f07000c
			public const int Play = 2131165196;
			
			// aapt resource value: 0x7f07000a
			public const int Record = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int SampleVideoView = 2131165197;
			
			// aapt resource value: 0x7f07000b
			public const int Stop = 2131165195;
			
			// aapt resource value: 0x7f070005
			public const int continuer = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int date = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int email = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int imageViewLogo = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int linearLayout1 = 2131165193;
			
			// aapt resource value: 0x7f070004
			public const int linearLayoutbottom = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int linearLayoutmid = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int linearLayouttop = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int password = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Inscription = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MenuConnexion = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MenuPrincipal = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int VideoPrise = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
